# Marked Blog Config

# Site
site_name: StanZhai::Blog
sub_title: 好记性不如烂键盘！
description: 翟士丹的技术博客，爱编码，爱生活，有梦想，不抱怨。
author: StanZhai 翟士丹
email: jasondan325@163.com
language: zh-CN

# Url
url: http://blog.zhaishidan.cn
root: /
permalink: :year/:month/:day/:title/

# Database
## Marked Blog uses MongoDB as database server
## For Dev: mongodb://<user>:<password>@widmore.mongohq.com:10010/marked-blog
mongodb:
  host: localhost
  port: 27017
  db_name: marked-blog
  user_name: 
  password: 

# Server
## Marked Blog uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
admin_url: /admin
logger: false
logger_format:

# Theme
theme: light